const PERMISSIONS = [
  { name: 'DASHBOARD_VIEW', module: 'Dashboard', description: 'View dashboard stats, charts and activity' },
  { name: 'SEARCH', module: 'Dashboard', description: 'Use global search across modules' },
  { name: 'STUDENT_VIEW', module: 'Students', description: 'View student records' },
  { name: 'STUDENT_CREATE', module: 'Students', description: 'Create students (incl. CSV import)' },
  { name: 'STUDENT_UPDATE', module: 'Students', description: 'Update students and photos' },
  { name: 'STUDENT_DELETE', module: 'Students', description: 'Delete students' },
  { name: 'TEACHER_VIEW', module: 'Teachers', description: 'View teacher records' },
  { name: 'TEACHER_CREATE', module: 'Teachers', description: 'Create teachers' },
  { name: 'TEACHER_UPDATE', module: 'Teachers', description: 'Update teachers and photos' },
  { name: 'TEACHER_DELETE', module: 'Teachers', description: 'Delete teachers' },
  { name: 'CLASS_VIEW', module: 'Classes', description: 'View classes' },
  { name: 'CLASS_CREATE', module: 'Classes', description: 'Create classes' },
  { name: 'CLASS_UPDATE', module: 'Classes', description: 'Update classes' },
  { name: 'CLASS_DELETE', module: 'Classes', description: 'Delete classes' },
  { name: 'SUBJECT_VIEW', module: 'Subjects', description: 'View subjects' },
  { name: 'SUBJECT_CREATE', module: 'Subjects', description: 'Create subjects' },
  { name: 'SUBJECT_UPDATE', module: 'Subjects', description: 'Update subjects' },
  { name: 'SUBJECT_DELETE', module: 'Subjects', description: 'Delete subjects' },
  { name: 'EXAMS_VIEW', module: 'Exams', description: 'View exams' },
  { name: 'EXAMS_CREATE', module: 'Exams', description: 'Create exams' },
  { name: 'EXAMS_UPDATE', module: 'Exams', description: 'Update exams' },
  { name: 'EXAMS_DELETE', module: 'Exams', description: 'Delete exams' },
  { name: 'MARKS_VIEW', module: 'Marks', description: 'View marks and reports' },
  { name: 'MARKS_CREATE', module: 'Marks', description: 'Enter marks' },
  { name: 'MARKS_UPDATE', module: 'Marks', description: 'Update/save marks' },
  { name: 'ATTENDANCE_VIEW', module: 'Attendance', description: 'View attendance and reports' },
  { name: 'ATTENDANCE_CREATE', module: 'Attendance', description: 'Mark student attendance' },
  { name: 'ATTENDANCE_UPDATE', module: 'Attendance', description: 'Update attendance records' },
  { name: 'FEES_VIEW', module: 'Fees', description: 'View fee records' },
  { name: 'FEES_CREATE', module: 'Fees', description: 'Create fee records' },
  { name: 'FEES_UPDATE', module: 'Fees', description: 'Update fee records' },
  { name: 'FEES_DELETE', module: 'Fees', description: 'Delete fee records' },
  { name: 'NOTIFICATION_VIEW', module: 'Notifications', description: 'View notifications and mark read' },
  { name: 'NOTIFICATION_CREATE', module: 'Notifications', description: 'Create notifications' },
  { name: 'NOTIFICATION_MANAGE', module: 'Notifications', description: 'Delete/manage notifications' },
  { name: 'DOCUMENT_VIEW', module: 'Documents', description: 'View and download student documents' },
  { name: 'DOCUMENT_UPLOAD', module: 'Documents', description: 'Upload student documents' },
  { name: 'DOCUMENT_DELETE', module: 'Documents', description: 'Delete student documents' },
  { name: 'REPORT_VIEW', module: 'Reports', description: 'View reports' },
  { name: 'REPORT_PRINT', module: 'Reports', description: 'Print/Pdf reports (profiles, marksheets, receipts)' },
  { name: 'SETTINGS_VIEW', module: 'Settings', description: 'View school settings' },
  { name: 'SETTINGS_UPDATE', module: 'Settings', description: 'Update school settings and logo' },
  { name: 'AUDIT_VIEW', module: 'Audit', description: 'View audit logs and export' },
  { name: 'BACKUP_VIEW', module: 'Backup', description: 'View and download backups' },
  { name: 'BACKUP_CREATE', module: 'Backup', description: 'Create and delete backups' },
  { name: 'BACKUP_RESTORE', module: 'Backup', description: 'Restore a backup (Super Admin only by default)' },
  { name: 'USER_VIEW', module: 'Users', description: 'View users and roles' },
  { name: 'USER_CREATE', module: 'Users', description: 'Create users' },
  { name: 'USER_UPDATE', module: 'Users', description: 'Update users and assign roles' },
  { name: 'USER_DISABLE', module: 'Users', description: 'Enable/disable user accounts and reset passwords' },
  { name: 'TRANSPORT_VIEW', module: 'Transport', description: 'View transport module (vehicles, drivers, routes, assignments)' },
  { name: 'TRANSPORT_CREATE', module: 'Transport', description: 'Create transport records (vehicles, drivers, routes)' },
  { name: 'TRANSPORT_UPDATE', module: 'Transport', description: 'Update transport records and student assignments' },
  { name: 'TRANSPORT_DELETE', module: 'Transport', description: 'Delete transport records' },
  { name: 'TRANSPORT_FEES_VIEW', module: 'Transport', description: 'View transport fee records and summaries' },
  { name: 'TRANSPORT_FEES_MANAGE', module: 'Transport', description: 'Create and update transport fee records' },
  { name: 'TRANSPORT_REPORT_VIEW', module: 'Transport', description: 'View transport reports' },
  { name: 'TRANSPORT_REPORT_PRINT', module: 'Transport', description: 'Print/PDF transport reports' },
];

module.exports = { PERMISSIONS };